version: '3'
services:
  postgres:
    container_name: postgres-local
    image: postgres
    hostname: postgres
    ports:
      #- "6543:5432"
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pw
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@vivantehealth.interview
      PGADMIN_DEFAULT_PASSWORD: pw
    restart: unless-stopped

volumes:
  postgres-data:
