version: 2

models:
  - name: demographics
    description: Contains basic demographic information about survey respondents.

    columns:
      - name: id
        description: Unique identifier
        tests:
          - unique
          - not_null

  - name: examination
    description: Contains physical examination and lab test result information.

    columns:
      - name: id
        tests:
          - unique
          - not_null

  - name: utilization
    description: Contains information on type and frequency of various healthcare services used.

    columns:
      - name: id
        tests:
          - unique
          - not_null